# Nome della action
name: Deploy React App to GH pages

# "evento" che triggera la action
on:
  push:
    branches: [gh-pages]

# setup della action
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # versione di node.js da utilizzare
        node-version: [16]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: git config --global user.name 'Giuseppe Senettone'
      - run: git config --global user.email 'giu.sene@gmail.com'
      - run: npm run deploy

      ## Presa dal marketplace
      # - name: Deploy to gh-pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.PERSON_ACCESS_TOKEN_FOR_PUSH_TO_GH_PAGES_BRANCH }}
      #     publish_dir: ./build
